name: BlockSystem
version: 1.2
author: iTzDinikCZ
main: cz.dinohd.bs.Main
description: System pro server BlockMania!
depend: [Vault]
permissions:
  system.guest:
    default: true
    description: Zatim zadne vyuziti
  system.announce:
    default: false
  system.admin:
    default: false
  system.anvil:
    default: false
commands:
  announce:
    description: Speciální broadcast
    aliases: [shout, bc, broadcast, say]
  cc:
  softrestart:
  inv:
  inzerat:
  bsreload:
  particles:
  chatcolor:
  softcontroller:
  bsdownload:
  bsregenerate:
  ac:
  spawnboat:
  activatejumpingeffectcommand:
  event: